services:
  database:
    build: ./SchoolHub.DB
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=12345678
      - MYSQL_ROOT_PASSWORD=root

    volumes:
      - schoolhub-db:/var/lib/mysql

  backend:
    build: ./SchoolHub.API
    ports:
      - 80:80
    links:
      - "database:db"
    
  frontend:
    build: ./schoolHub.app
    ports:
      - 5000:5000
    
